### ISSUE TITLE
PHP namespaced classes are not analyzed

### ISSUE THREAD

**Issue by kenjis** [ytetsuro/sabik#58]
The following class is not included in the report.

```php
<?php

declare(strict_types=1);

namespace Kenjis\Test;

class Test
{
    public function test()
    {
    }
}
```

The following class is included.

```php
<?php

declare(strict_types=1);

class Test
{
    public function test()
    {
    }
}
```

**Comment by ytetsuro** [comment]
Thank you for reporting the issue.
We were able to reproduce the issue and have fixed it.

Very very thanks.

**Comment by kenjis** [comment]
It worked! Thanks.

<img width="1277" alt="sabik-report" src="https://user-images.githubusercontent.com/87955/106337481-9d810800-62d4-11eb-990b-40e8b5c5fa0d.png">
