### ISSUE TITLE
It takes time to open HTML report

### ISSUE THREAD

**Issue by kenjis** [ytetsuro/sabik#70]
There are three files with starting `index.`.

```
$ open sabik_report/index. ← press [tab] key twice
index.css   index.html  index.js    
```

So I can't open `index.html` quickly.

If you rename `index.css` and `index.js`, we can open like this:

```
$ open sabik_report/i ← press [tab] key and [enter] key
```

**Comment by ytetsuro** [comment]
Very thanks issue.
fixed!!
